#!/usr/bin/env bash
# DisplayS "Best School" 10 times using while loop.
# On the 9th iteration, displays "Best School" and then "Hi" on a new line.

count=0

while [ $count -lt 10 ]
do
        if [ $count -eq 9 ]
        then
              echo "Best School"
        fi
                      echo "Hi"
                   (( count ++ ))
done
